### ISSUE TITLE
Add custom integrations

### ISSUE THREAD

**Issue by Tobbes1990** [albaintor/UC-Remote-Two-Toolkit#2]
### Description

When I try to add the LG or Kodi integration, the toolkit failed with the message “The filename should not have special characters”. I don’t rename the integration i’ve downloaded. Is it my fault?

The file I downloaded is named “uc-intg-lgtv-v1.2.2-aarch64-20240921_143547.tar.gz”

### How to Reproduce

1. click on add integration 
2. search for the downloaded file
3. click add
4. pop up the red message

### Expected behavior

The integration should be added

**Comment by albaintor** [comment]
Which firmware version do you have ?
When you download a file, sometimes the browser adds parenthesis to the file name when it is duplicate.
The file name you show looks correct though

**Comment by Tobbes1990** [comment]
I'm on the latest firmware (not on a beta firmware). I turned on beta firmware updates, but there's no new firmware found.

**Comment by albaintor** [comment]
You need the latest beta firmware, it won't work else. When enabled, you need to reboot the remote and search again for updates
